#!/usr/bin/env python3
"""Generates frontend/lib/whoGrowthData.ts from the WHO Child Growth Standards tables (0-60 months, LMS method).

Source: the `pygrowup` package, which ships WHO's published tables.
    pip download pygrowup --no-deps && tar xzf pygrowup-*.tar.gz
    python3 tools/generate-who-growth.py pygrowup-0.8.2/pygrowup/tables
Also verifies each table's own SD columns against values recomputed from L, M, S.
"""
import json, os, sys

src = sys.argv[1]
files = {  # metric -> file stem (0-5 years, monthly)
    'wfa': 'wfa_{sex}_0_5_zscores.json',   # weight (kg) for age
    'lhfa': 'lhfa_{sex}_0_5_zscores.json', # length/height (cm) for age
    'hcfa': 'hcfa_{sex}_0_5_zscores.json', # head circumference (cm) for age
}
sd_cols = {'SD3neg': -3, 'SD2neg': -2, 'SD1neg': -1, 'SD0': 0, 'SD1': 1, 'SD2': 2, 'SD3': 3}

def value_at(L, M, S, z):
    return M * (1 + L * S * z) ** (1 / L) if L != 0 else M * 2.718281828459045 ** (S * z)

out = {}
worst = 0
for metric, pattern in files.items():
    out[metric] = {}
    for sex in ('boys', 'girls'):
        rows = json.load(open(os.path.join(src, pattern.format(sex=sex))))
        rows.sort(key=lambda r: int(r['Month']))
        # the length-for-age table lists month 24 twice: recumbent length, then standing height (they differ by ~1.4 cm).
        # Keep length up to 23 months and standing height from 24 months, as WHO does.
        dedup = {}
        for r in rows:
            dedup[int(r['Month'])] = r  # later rows win, so month 24 is the standing-height row
        rows = [dedup[m] for m in sorted(dedup)]
        assert [int(r['Month']) for r in rows] == list(range(61)), (metric, sex, 'months 0..60')
        lms = []
        for r in rows:
            L, M, S = float(r['L']), float(r['M']), float(r['S'])
            lms.append([L, M, S])
            for col, z in sd_cols.items():
                if col in r:
                    diff = abs(value_at(L, M, S, z) - float(r[col]))
                    worst = max(worst, diff)
                    # the published SD columns are rounded to 1 decimal
                    assert diff < 0.08, (metric, sex, r['Month'], col, diff)
        out[metric][sex] = lms
print('verified: recomputed SD curves match the published tables, worst difference %.3f' % worst)

ts = '''// GENERATED by tools/generate-who-growth.py: do not edit by hand.
// WHO Child Growth Standards (0-60 months), LMS parameters per completed month, [L, M, S].
// Source: World Health Organization, https://www.who.int/tools/child-growth-standards
// Check the WHO's terms of use before using these tables in a commercial product.
export type Sex = 'boys' | 'girls';
export type GrowthMetric = 'wfa' | 'lhfa' | 'hcfa'; // weight / length-height / head circumference for age
export const WHO_LMS: Record<GrowthMetric, Record<Sex, number[][]>> = ''' + json.dumps(out, separators=(',', ':')) + ';\n'
open(os.path.join(os.path.dirname(__file__), '..', 'frontend', 'lib', 'whoGrowthData.ts'), 'w').write(ts)
print('wrote frontend/lib/whoGrowthData.ts (%d bytes)' % len(ts))
